### PR TITLE
Added Czech translation

### PR DESCRIPTION
**Pull request by hejsekvojtech**

### CODE REVIEW

**Comment by berkantkz** [comment]
Thanks for your contribution. Everything seems to be nice except the ```update``` variables in each post. But the code for Czech you set as ```cs```. Is it not ```cz```?

Also, please push a new commit with which changes the ```update``` variables.

~~In addition, you forgot to add ```index-*czech-code*.html``` on root~~ You already did that. My bad, sorry.

**Comment by hejsekvojtech** [comment]
Both cs and cz are correct for Czech language.

**Comment by berkantkz** [comment]
Thanks a lot. After you make the changes that I mentioned above, I'll merge your pull request.

**Comment by hejsekvojtech** [comment]
Done! Ready to merge

**Comment by berkantkz** [comment]
Thank you for your work, mate!

**Comment by berkantkz** [comment]
Please can you translate newly added strings?

**Pull request merged**
